import streamlit as st
import uuid

from src.auth import authenticate_user
from src.agent import graph

from langchain.messages import AIMessage, ToolMessage

# Config

st.set_page_config(
    page_title="ParcelPilot",
    page_icon="📦",
)

# Authentication
def login(email: str, password: str):
    return authenticate_user(email, password)

# Login Page

if "user_context" not in st.session_state:

    st.title("📦 ParcelPilot")
    st.subheader("Customer Support")

    email = st.text_input("Email")
    password = st.text_input(
        "Password",
        type="password",
    )

    if st.button("Login"):

        if not email or not password:
            st.warning("Please enter your email and password.")
            st.stop()

        user_context = login(email, password)

        if user_context is None:
            st.error("Invalid credentials.")
        else:
            # Store authenticated session information
            st.session_state.user_context = user_context
            st.session_state.thread_id = str(uuid.uuid4())
            st.session_state.messages = []

            st.rerun()

    st.stop()


# Logged-in state

user_context = st.session_state.user_context

if "messages" not in st.session_state:
    st.session_state.messages = []

# Header

st.title("📦 ParcelPilot")

st.success("Logged in successfully!")

st.write(f"**Account:** {user_context.account_name}")
st.write(f"**User:** {user_context.name}")

# Chat History & Interface

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.write(message["content"])

# Chat Input

if prompt := st.chat_input("Ask ParcelPilot..."):

    st.session_state.messages.append({
        "role": "user",
        "content": prompt,
    })

    with st.chat_message("user"):
        st.write(prompt)

    with st.chat_message("assistant"):

        status = st.status(
            "🤖 ParcelPilot is working...",
            expanded=True,
        )

        response_placeholder = st.empty()

        tools_used = []
        response_text = ""

        config = {
            "configurable": {
                "thread_id": st.session_state.thread_id,
            }
        }

        for chunk in graph.stream(
            {
                "messages": [
                    {
                        "role": "user",
                        "content": prompt,
                    }
                ],
                "user_context": st.session_state.user_context,
            },
            config=config,
            stream_mode=["updates", "messages"],
            version="v2",
        ):

            # ------------------------------------------
            # LLM tokens
            # ------------------------------------------

            if chunk["type"] == "messages":

                token, metadata = chunk["data"]

                # Only display tokens generated by the chatbot node.
                # Tool outputs are intentionally hidden.
                if (
                    metadata.get("langgraph_node") == "chatbot"
                    and token.content
                ):
                    response_text += token.content
                    response_placeholder.markdown(response_text)

            # ------------------------------------------
            # Graph / tool updates
            # ------------------------------------------

            elif chunk["type"] == "updates":

                data = chunk["data"]

                for node_name, update in data.items():

                    if node_name == "chatbot":

                        for message in update.get("messages", []):

                            if hasattr(message, "tool_calls"):

                                for tool_call in message.tool_calls:

                                    tool_name = tool_call["name"]

                                    if tool_name not in tools_used:
                                        tools_used.append(tool_name)

                                        status.write(
                                            f"🔧 Calling `{tool_name}`..."
                                        )

                    elif node_name == "tools":

                        for message in update.get("messages", []):

                            tool_name = getattr(
                                message,
                                "name",
                                None,
                            )

                            if tool_name:
                                status.write(
                                    f"✓ `{tool_name}` completed"
                                )

        status.update(
            label="✅ Response generated",
            state="complete",
            expanded=False,
        )

    st.session_state.messages.append({
        "role": "assistant",
        "content": response_text,
    })